### ISSUE TITLE
vite.config.ts

### ISSUE THREAD

**Issue by serhiyhvala** [VMekh8/MuseumASPCoreSite#21]
If you don't plan to use file extensions like ```.jsx``` or ```.tsx```, you can remove this dependency

```bash
npm uninstall @vitejs/plugin-vue-jsx
```

![CleanShot 2024-04-29 at 18 13 50](https://github.com/VMekh8/MuseumASPCoreSite/assets/88881670/10916c31-80e1-4d55-af71-ff141d0181fd)

**Comment by VMekh8** [comment]
have a build error when remove this plugin
