### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by serhiyhvala** [VMekh8/MuseumASPCoreSite#24]
https://github.com/VMekh8/MuseumASPCoreSite/blob/0f4921e2b8e5a7740ac3cdf4836caef3ce9c1a2d/MuseumSite/MuseumSite/src/layouts/UserLayout/Login.vue#L22

Such things as links and all sorts of "dangerous" things are better to put in the ```.env``` file

```
API_BASE_URL=`https://localhost:7105`
```

And since you're using vite, you should use the values from .env as follows:

```js
const responce = await fetch(`${import.meta.env.API_URL}/Account/Login`, {
  email: this.email,
  password: this.password
});
```

Or even better, make a separate folder, ```config```, which will contain the file ```index.ts``` and will contain the following value:

```js
export const API_BASE_URL = import.meta.env.API_URL
```

After that, you will use it like this:

```js
import { API_BASE_URL } from "@/config"

// code
const responce = await fetch(`${API_BASE_URL}/Account/Login`, {
  email: this.email,
  password: this.password
});
```

Although there are even better ways, it's up to you to do it at your own discretion

[You can read more about env variables in vite here](https://vitejs.dev/guide/env-and-mode)

P.S.

Don't forget to update .gitignore after you create the .env file

```gitignore
.env
```

PP.SS.

It's also a good practice to create an additional .env.example file. It doesn't affect anything, but in the future, you may forget what keys you used and what they mean (or not only you may forget). You don't need to write this file in .gitignore anymore, you need to commit it

PPP.SSS

Every time you change your .env variables, you need to restart the server

**Comment by VMekh8** [comment]
Done with env ✅
